### ISSUE TITLE
PgCsv.new - undefined method symbolize_keys' 

### ISSUE THREAD

**Issue by lucaspottersky** [kostya/pg_csv#3]
This gem if throwing the following exception when you try to `PgCsv.new`

`/home/.gem/ruby/2.1.3/gems/pg_csv-0.1.8/lib/pg_csv.rb:9:in `initialize': undefined method `symbolize_keys' for #<Hash:0x007f55ba0ee9a0> (NoMethodError)`

**Comment by kostya** [comment]
hm symbolize keys defined in active_support, which should require if you use active_record. anyway just remove this.
